### Register user
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "email": "john.doe@sixpack.com",
	"password": "h+z67{GxLSL~]Cl(I88AqV7w"
}

### Login
POST http://localhost:3000/users/login HTTP/1.1
content-type: application/json

{
    "email": "john.doe@sixpack.com",
	"password": "h+z67{GxLSL~]Cl(I88AqV7w"
}

### Account activation
GET http://localhost:3000/users/activate/926c7bed-18a7-4c0f-97fd-f5901b2c52ba HTTP/1.1
content-type: application/json
