### Register user
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "email": "boban.acimovic@gmail.com",
	"password": "h+z67{GxLSL~]Cl(I88AqV7w"
}

### Login
POST http://localhost:3000/users/login HTTP/1.1
content-type: application/json

{
    "email": "boban.acimovic@gmail.com",
	"password": "h+z67{GxLSL~]Cl(I88AqV7w"
}

### Account activation
GET http://localhost:3000/users/activate/926c7bed-18a7-4c0f-97fd-f5901b2c52ba HTTP/1.1

### Request password reset
POST http://localhost:3000/users/reset-password HTTP/1.1
content-type: application/json

{
    "email": "boban.acimovic@gmail.com"
}

### Reset password
PATCH http://localhost:3000/users/reset-password HTTP/1.1
content-type: application/json

{
    "passwordResetToken": "926c7bed-18a7-4c0f-97fd-f5901b2c52ba",
    "password": "h+z67{GxLSL~]Cl(I88AqV7w"
}

### Check password strength
POST http://localhost:3000/users/check-password HTTP/1.1
content-type: application/json

{
    "password": "h+z67{GxLSL~]Cl(I88AqV7w"
}
