definitions:
  request.Email:
    properties:
      email:
        type: string
    type: object
  request.Password:
    properties:
      password:
        type: string
    type: object
  request.ResetPassword:
    properties:
      password:
        type: string
      passwordResetToken:
        type: string
    type: object
  request.UserLogin:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  request.UserRegistration:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  response.Error:
    properties:
      error:
        type: string
    type: object
  response.User:
    properties:
      authToken:
        type: string
      created:
        type: string
      email:
        type: string
      id:
        format: uuid
        type: string
      refreshToken:
        type: string
      updated:
        type: string
    type: object
info:
  contact: {}
  description: REST API providing user accounting and authentication
  license:
    name: BSD-2-Clause-Patent
    url: https://github.com/ectobit/arc/blob/main/LICENSE
  title: Arc
paths:
  /users:
    post:
      consumes:
      - application/json
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/request.UserRegistration'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: ""
      summary: Register user account.
      tags:
      - users
  /users/activate/{token}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Activation token
        in: path
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: ""
      summary: Activate user account.
      tags:
      - users
  /users/check-password:
    post:
      consumes:
      - application/json
      parameters:
      - description: Password
        in: body
        name: password
        required: true
        schema:
          $ref: '#/definitions/request.Password'
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
      summary: Calculate password strength.
      tags:
      - users
  /users/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/request.UserLogin'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: ""
      summary: Login.
      tags:
      - users
  /users/reset-password:
    patch:
      consumes:
      - application/json
      parameters:
      - description: Password reset token and new password
        in: body
        name: resetPassword
        required: true
        schema:
          $ref: '#/definitions/request.ResetPassword'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: ""
      summary: Set new user's password.
      tags:
      - users
    post:
      consumes:
      - application/json
      parameters:
      - description: E-mail address
        in: body
        name: email
        required: true
        schema:
          $ref: '#/definitions/request.Email'
      produces:
      - application/json
      responses:
        "202":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: ""
      summary: Request password reset.
      tags:
      - users
swagger: "2.0"
